Add bindings documentation and CI check

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -67,11 +67,20 @@ jobs:
             roboplan-ros-pixi:ci \
             bash -c "
               pixi run -e ${{ matrix.ros_distro }} setup-colcon && \
-              pixi run -e ${{ matrix.ros_distro }} build && \
+              pixi run -e ${{ matrix.ros_distro }} build-no-symlink && \
               pixi run -e ${{ matrix.ros_distro }} test && \
               pixi run -e ${{ matrix.ros_distro }} test-result && \
               chmod -R a+rwX /workspace/.sccache
             "
+      - name: Check bindings stub files
+        run: |
+          if ! git diff --exit-code --shortstat -- 'roboplan_ros_cpp/roboplan_ros_cpp/*.pyi'; then
+            echo "::error::The .pyi stub files are out of sync with the source code. Make sure to rebuild the Python bindings without symlink builds using 'pixi run -e ${ROS_DISTRO} build-no-symlink' and commit the changes."
+            echo "Git Diff:"
+            git diff -- 'roboplan_ros_cpp/roboplan_ros_cpp/*.pyi'
+            exit 1
+          fi
+          echo "✅ .pyi stub files look good!"
 
   # Build ROS docker images and run tests.
   ros_build_and_test:
