Add bindings documentation and CI check (#37)
* Add bindings documentation and CI check

* No symlinks

* Add the stubs

* Fix pre-commit exclusions

* Try use init python class content

* Both

* Add docs for viz bindings

* actually add the docs

* add stubs to ci checks

---------

Co-authored-by: Erik Holum <eholum@gmail.com>

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -72,6 +72,19 @@ jobs:
               pixi run -e ${{ matrix.ros_distro }} test-result && \
               chmod -R a+rwX /workspace/.sccache
             "
+      - name: Check bindings stub files
+        run: |
+          STUB_PATHS="
+            roboplan_ros_cpp/roboplan_ros_cpp/*.pyi
+            roboplan_ros_visualization/roboplan_ros_visualization/*.pyi
+          "
+          if ! git diff --exit-code --shortstat -- $STUB_PATHS; then
+            echo "::error::The .pyi stub files are out of sync with the source code. Make sure to rebuild the Python bindings with 'pixi run -e ${ROS_DISTRO} build' and commit the changes."
+            echo "Git Diff:"
+            git diff -- $STUB_PATHS
+            exit 1
+          fi
+          echo "✅ .pyi stub files look good!"
 
   # Build ROS docker images and run tests.
   ros_build_and_test:
